# Generated by Django 4.2.4 on 2023-10-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_userall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userall',
            new_name='userall_id',
        ),
    ]
