# Generated by Django 4.2.4 on 2023-10-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
