# Generated by Django 4.2.4 on 2023-10-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
