# Generated by Django 4.2.4 on 2023-10-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_profilepicture_userprofile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categery',
            new_name='category',
        ),
    ]
